[package]
name = "image-packer"
version = "0.1.0"
authors = ["tkaaad97 <tkaaad97@gmail.com>"]
edition = "2018"

[dependencies]
clap = "^3.0.0"
image = "^0.24"
rand = "^0.8"

[dev-dependencies]
proptest = "^1.0"

[[bin]]
name = "image-gen"
path = "src/bin/image-gen.rs"
test = false
bench = false
